Repository storybookjs/eslint-plugin-storybook, pull requests merged in 2021-11, with the labels that each got.

#18 Fix use-storybook-testing-library default export handling
  lib/rules/use-storybook-testing-library.js
  tests/lib/rules/use-storybook-testing-library.js
Labels: bug

#29 default-exports: target first non-import nodes when reporting
  lib/rules/default-exports.ts
  tests/lib/rules/default-exports.test.ts
Labels: release, patch

#32 no-title-property-in-meta: fix dangling comma and highlighting
  lib/rules/no-title-property-in-meta.ts
  tests/lib/rules/no-title-property-in-meta.test.ts
Labels: bug

#36 Add autofix heuristics for default-exports rule
  lib/rules/csf-component.ts
  lib/rules/default-exports.ts
  tests/lib/rules/default-exports.test.ts
Labels: enhancement, release, minor

#37 hierarchy-separator: remove dot from checkings
  lib/rules/hierarchy-separator.ts
  tests/lib/rules/hierarchy-separator.test.ts
Labels: release, patch

#38 prefer-pascal-case: ignore stories that start with underscore
  lib/rules/prefer-pascal-case.ts
  tests/lib/rules/prefer-pascal-case.test.ts
Labels: release, patch

#39 ignore storiesOf in default-export and prefer-pascal-case
  lib/rules/default-exports.ts
  lib/rules/prefer-pascal-case.ts
  tests/lib/rules/default-exports.test.ts
  tests/lib/rules/prefer-pascal-case.test.ts
Labels: release, patch

#41 simplify override file regex
  lib/configs/addon-interactions.ts
  lib/configs/csf.ts
  lib/configs/recommended.ts
  tools/update-configs.ts
Labels: release, patch

#44 Rule: add story-exports
  README.md
  docs/rules/story-exports.md
  lib/configs/csf.ts
  lib/configs/recommended.ts
  lib/rules/story-exports.ts
  tests/lib/rules/story-exports.test.ts
  tools/generate-rule.ts
Labels: release, minor

#46 Unify documentation to use @storybook/jest
  docs/rules/use-storybook-expect.md
  lib/rules/use-storybook-expect.ts
  tests/lib/rules/use-storybook-expect.test.ts
Labels: release, patch

#51 Fix await interactions use cases
  lib/rules/await-interactions.ts
  lib/utils/ast.ts
  tests/lib/rules/await-interactions.test.ts
Labels: bug, release, patch

#53 Rule: pass context when invoking play
  README.md
  docs/rules/context-in-play-function.md
  lib/configs/addon-interactions.ts
  lib/configs/recommended.ts
  lib/rules/context-in-play-function.ts
  lib/utils/ast.ts
  package.json
  tests/lib/rules/context-in-play-function.test.ts
  yarn.lock
Labels: release, minor, new rule

#55 Fix: define hasSuggestions to all fixable rules
  README.md
  lib/rules/await-interactions.ts
  lib/rules/default-exports.ts
  lib/rules/hierarchy-separator.ts
  lib/rules/no-redundant-story-name.ts
  lib/rules/no-title-property-in-meta.ts
  lib/rules/prefer-pascal-case.ts
  lib/rules/story-exports.ts
  lib/rules/use-storybook-expect.ts
  lib/rules/use-storybook-testing-library.ts
  tools/generate-rule.ts
Labels: release, patch
