Repository storybookjs/eslint-plugin-storybook, pull requests merged in 2024-11, with the labels that each got.

#176 Fix: Bring back non-categorized rules
  README.md
  docs/rules/await-interactions.md
  docs/rules/csf-component.md
  docs/rules/default-exports.md
  docs/rules/meta-inline-properties.md
  docs/rules/no-stories-of.md
  docs/rules/prefer-pascal-case.md
  docs/rules/story-exports.md
  docs/rules/use-storybook-expect.md
  docs/rules/use-storybook-testing-library.md
  lib/index.ts
  tests/integrations/flat-config.spec.ts
  tests/integrations/flat-config/a.stories.tsx
  tests/integrations/flat-config/eslint.config.js
  tests/integrations/legacy-config.spec.ts
  tests/integrations/legacy-config/.eslintrc.json
  tests/integrations/legacy-config/a.stories.tsx
  tools/update-rules-list.ts
  tools/utils/categories.ts
  tools/utils/docs.ts
  tools/utils/rules.ts
Labels: patch

#163 chore: Update the link for eslintignore doc
  README.md
  docs/rules/no-uninstalled-addons.md
Labels: skip-release

#179 Update docs to be more clear about extended categories
  README.md
  docs/rules/csf-component.md
  docs/rules/default-exports.md
  docs/rules/hierarchy-separator.md
  docs/rules/no-redundant-story-name.md
  docs/rules/story-exports.md
  tools/update-rules-list.ts
Labels: skip-release

#180 Generate Typescript types for flat configs
  tsconfig.build.json
Labels: minor
