Repository storybookjs/eslint-plugin-storybook, pull requests merged in 2025-03, with the labels that each got.

#194 feat: Support storybook/test for expect imports
  README.md
  lib/rules/use-storybook-expect.ts
  tests/lib/rules/use-storybook-expect.test.ts
Labels: patch

#195 fix(peer-deps): Add support for typescript 5.8
  package.json
  pnpm-lock.yaml
Labels: patch, dependencies

#192 fix: allows self-referencing context in play function
  docs/rules/context-in-play-function.md
  lib/rules/context-in-play-function.ts
  tests/lib/rules/context-in-play-function.test.ts
Labels: bug, patch

#197 Modernize codebase (tsup, vitest, etc.)
  .github/workflows/test.yml
  .prettierrc.d.ts
  README.md
  docs/rules/no-renderer-packages.md
  lib/configs/csf-strict.ts
  lib/configs/flat/recommended.ts
  lib/configs/recommended.ts
  lib/index.ts
  lib/rules/await-interactions.ts
  lib/rules/default-exports.ts
  lib/rules/no-renderer-packages.ts
  lib/rules/no-stories-of.ts
  lib/rules/prefer-pascal-case.ts
  lib/rules/story-exports.ts
  lib/rules/use-storybook-expect.ts
  lib/utils/create-storybook-rule.ts
  package.json
  pnpm-lock.yaml
  tests/integrations/flat-config.spec.ts
  tests/integrations/legacy-config.spec.ts
  tests/lib/rules/no-renderer-packages.test.ts
  tests/lib/rules/no-uninstalled-addons.test.ts
  tools/generate-rule.ts
  tools/update-lib-configs.ts
  tools/update-lib-flat-configs.ts
  tools/update-lib-index.ts
  tools/utils/categories.ts
  tools/utils/updates.ts
  tsconfig.build.json
  tsconfig.json
  tsconfig.test.json
  tsup.config.ts
  vitest.config.ts
  vitest.d.ts
  vitest.integration.config.ts
Labels: tests, dependencies

#200 Add meta-satisfies-type rule (rebased)
  README.md
  docs/rules/meta-satisfies-type.md
  lib/index.ts
  lib/rules/meta-satisfies-type.ts
  tests/lib/rules/meta-satisfies-type.test.ts
  tools/utils/categories.ts
Labels: release, minor
